# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1c6635db66c53dc14899ebc6ce4d15b51aa5ecf50a99d09bf0898f6824bca3c7d2d4227c166f5bd9f50738c66fbd9c330c74949ba711cd3860987e8e7355b0ad

test:
  secret_key_base: e1a3318174f913b9b5559148f24acca315a0d6534cc5062ae26d84625e8fb480623ba99dc450ad17807d0c5586d96381a62b025a6f75e505f36ec2d5ee6b160c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
